import baseType from './src/baseType';
import typeAsserts from './src/typeAsserts';
import functionType from './src/functionType';
import classType from './src/classType';
import interfaceAndGeneric from './src/interfaceAndGeneric';
import crossType from './src/crossType';
import conditionType from './src/conditionBuiltinType';
import objectKeysType from './src/keysBuiltinType';
import infer from './src/infer';
import compatibility from './src/compatibility';

baseType();
typeAsserts();
functionType();
classType();
interfaceAndGeneric();
crossType();
conditionType();
objectKeysType();
infer();
compatibility();